scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:9090']

  - job_name: 'address-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ['host.docker.internal:8082']
        labels:
          group: 'dev'
          service: 'address-service'

  - job_name: 'student-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          group: 'dev'
          service: 'student-service'

  - job_name: 'flaky-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ['host.docker.internal:8085']
        labels:
          group: 'dev'
          service: 'flaky-service'

  - job_name: 'spring-cloud-gateway'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ['host.docker.internal:9000']
        labels:
          group: 'dev'
          service: 'spring-cloud-gateway'