{
 "title": "Spring Boot Application",
 "description": "Dashboard for Spring Boot application with Micrometer",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(http_server_requests_seconds_count{application=\"$application\"}, instance)"
   },
   {
    "name": "uri",
    "label": "URI",
    "query": "label_values(http_server_requests_seconds{application=\"$application\", instance=~\"$instance\"}, uri)"
   }
  ]
 },
 "panels": [
  { "title": "Chaos Monkey", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Chaos Monkey Status",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "chaos_monkey_status{application=\"$application\"}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(chaos_monkey_application_request_count_total{application=\"$application\", type=\"total\"}[15s])",
     "legendFormat": "Total requests"
    },
    {
     "expr": "increase(chaos_monkey_application_request_count_total{application=\"$application\", type=\"assaulted\"}[15s])",
     "legendFormat": "Assaulted requests"
    }
   ]
  },
  {
   "title": "Latency Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(chaos_monkey_assault_latency_count_total{application=\"$application\"}[15s])"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "increase(chaos_monkey_assault_latency_count_gauge{application=\"$application\"}[15s])"
    }
   ]
  },
  {
   "title": "Total Exceptions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(chaos_monkey_assault_exception_count_total{application=\"$application\"}[15s])"
    }
   ]
  },
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Total Requests",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 8 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=~\"$instance\", uri=~\"$uri\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=~\"$instance\", uri=~\"$uri\", status!=\"200\"}[$__interval])) / sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=~\"$instance\", uri=~\"$uri\"}[$__interval])) * 100"
    }
   ]
  },
  {
   "title": "Failed Requests",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 12 },
   "format": "locale",
   "valueName": "range",
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=~\"$instance\", uri=~\"$uri\", status!=\"200\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Req / sec",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 12 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(http_server_requests_seconds_count{application=\"$application\", instance=~\"$instance\", uri=~\"$uri\"}[1m]))"
    }
   ]
  },
  {
   "title": "Log Event (1m)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(logback_events_total{application=\"$application\", instance=~\"$instance\", uri=~\"$uri\"}[1m])",
     "legendFormat": "{{level}}"
    }
   ]
  },
  { "title": "Http Server Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Avg",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 26 },
   "format": "dtdurations",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(http_server_requests_seconds_sum{application=\"$application\", instance=~\"$instance\", uri=~\"$uri\"}[1m])) / sum(irate(http_server_requests_seconds_count{application=\"$application\", instance=~\"$instance\", uri=~\"$uri\"}[1m]))"
    }
   ]
  },
  {
   "title": "Median",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 26 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds{application=\"$application\", instance=~\"$instance\", uri=~\"$uri\", quantile=\"0.5\"})"
    }
   ]
  },
  {
   "title": "p90",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 26 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds{application=\"$application\", instance=~\"$instance\", uri=~\"$uri\", quantile=\"0.9\"})"
    }
   ]
  },
  {
   "title": "p95",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 26 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds{application=\"$application\", instance=~\"$instance\", uri=~\"$uri\", quantile=\"0.95\"})"
    }
   ]
  },
  {
   "title": "p99",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 26 },
   "format": "dtdurations",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds{application=\"$application\", instance=~\"$instance\", uri=~\"$uri\", quantile=\"0.99\"})"
    }
   ]
  },
  {
   "title": "Max",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 26 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_max{application=\"$application\", instance=~\"$instance\", uri=~\"$uri\"})"
    }
   ]
  },
  {
   "title": "Response Time (percentile)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=~\"$instance\", uri=~\"$uri\"}[15s])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=~\"$instance\", uri=~\"$uri\"}[15s])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=~\"$instance\", uri=~\"$uri\"}[15s])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=~\"$instance\", uri=~\"$uri\"}[15s])) by (le))",
     "legendFormat": "99%"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_count{application=\"$application\", instance=~\"$instance\", uri=~\"$uri\"}[15s]) ",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Top 10 Most Used API endpoints",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by(uri, method) (rate(http_server_requests_seconds_count{application=\"$application\", instance=~\"$instance\", uri=~\"$uri\"}[1m])))"
    }
   ]
  },
  {
   "title": "Top 10 Slowest API endpoints",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by(uri, method) (rate(http_server_requests_seconds_max{application=\"$application\", instance=~\"$instance\", uri=~\"$uri\"}[1m])))"
    }
   ]
  },
  {
   "title": "Http Client Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Response Time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 21, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_client_requests_seconds_sum{application=\"$application\", instance=~\"$instance\", uri=~\"$uri\"}[1m])) / sum(rate(http_client_requests_seconds_count{application=\"$application\", instance=~\"$instance\", uri=~\"$uri\"}[1m]))"
      }
     ]
    },
    {
     "title": "Max Response Time",
     "type": "singlestat",
     "gridPos": { "h": 9, "w": 3, "x": 21, "y": 53 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(http_client_requests_seconds_max{application=\"$application\", instance=~\"$instance\", uri=~\"$uri\"})"
      }
     ]
    }
   ]
  }
 ]
}