spring:
  application:
    name: eureka-server
  security:
    basic:
      enabled: true
    user:
      name: eureka
      password: password


server:
  port: 8761

eureka:
  instance:
    hostname: eureka1
  client:
    serviceUrl:
      defaultZone: http://eureka:password@eureka2:8762/eureka/
